---
name: Build Hugo site

on:
  workflow_call:
    inputs:
      # inputs.build-readme-as-index: true
      build-readme-as-index:
        default: false
        description: '(Boolean) Whether to use `README.md` files as folder index (instead of `_index.md` files).'
        required: false
        type: boolean
      # inputs.config-file: ''
      config-file:
        description: '(String) Path to the Hugo configuration file'
        required: false
        type: string
      # inputs.config-params: {}
      config-params:
        default: |
          {}
        description: '(String) Hugo params configuration JSON'
        required: false
        type: string
      # inputs.config-ignore-files: 'go.*, hugo.yml, public/*'
      config-ignore-files:
        default: >
          "go.*",
          "hugo.yml",
          "public/*"
        description: '(String) Comma-separated list of file patterns to ignore in the Hugo build'
        required: false
        type: string
      # inputs.config-root-keys: ''
      config-root-keys:
        default: |
          "disableHugoGeneratorInject": true,
          "languageCode": "en-us"
        description: '(String) Configuration JSON for in the root of the Hugo config'
        required: false
        type: string
      # inputs.config-module-imports: ''
      # For a full list of options see: https://gohugo.io/configuration/module/#imports
      config-module-imports:
        description: '(String) Hugo module imports JSON. Objects with a "path" property.'
        required: false
        type: string
      # inputs.config-module-mounts: ''
      # For a full list of options see: https://gohugo.io/configuration/module/#mounts
      config-module-mounts:
        description: '(String) Hugo module mounts JSON. Objects with a "source" and "target" property.'
        required: false
        type: string
      # inputs.css: ''
      css:
        description: '(String) Custom CSS to include in the Hugo build'
        required: false
        type: string
      # inputs.docker-image: hugomods/hugo:std-go-git
      # For specific features see https://docker.hugomods.com/choose/
      docker-image:
        default: hugomods/hugo:std-go-git
        description: '(String) Docker image to use for building the Hugo site'
        required: false
        type: string
      # inputs.exclude: '.git\n.github'
      exclude:
        default: |
          .git
          .github
        description: '(String) Newline-separated list of file patterns to exclude from the GitHub Pages artifact'
        required: false
        type: string
      # inputs.path: ./
      path:
        default: ./
        description: '(String) Path to build the Hugo site from'
        required: false
        type: string

jobs:
  build:
    name: Build Hugo site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - id: custom-css
        name: Add custom CSS
        run: |
          sCssFile='_/custom.css'

          mkdir -p "$(dirname "${sCssFile}")"

          cat > "${sCssFile}" << 'END_OF_CSS'
          ${{ inputs.css }}
          END_OF_CSS

          sMount=''
          if [[ $(wc -w < "${sCssFile}") -gt 0 ]]; then
              printf -v sMount \
                '{ "source": "%s", "target": "assets/css/custom.css" }' \
                "${sCssFile}"

              if [[ "${{ inputs.config-module-mounts }}" != "" ]]; then
                  sMount="${sMount},"
              fi
          fi

          echo "css_mount=${sMount}" >> "$GITHUB_OUTPUT"

      - if: ${{ inputs.config-file == '' }}
        name: Create Hugo config file
        run: |
          cat <<JSON > hugo.json
          {
              ${{ inputs.config-root-keys }},
              "ignorefiles": [ ${{ inputs.config-ignore-files }} ],
              "module": {
                  "imports": [
                      ${{ inputs.config-module-imports }}
                  ],
                  "mounts": [
                      ${{ steps.custom-css.outputs.css_mount }}
                      ${{ inputs.config-module-mounts }}
                  ]
              },
              "params": ${{ inputs.config-params }}
          }
          JSON

      - if: ${{ inputs.config-file == '' }}
        name: Lint Hugo config JSON file
        uses: docker://pipelinecomponents/jsonlint:latest
        with:
          args: jsonlint hugo.json

      - id: config-file-path
        name: Set config file path
        run: |
          if [[ -n "${{ inputs.config-file }}" && -f "${{ inputs.config-file }}" ]]; then
            echo "Using provided config file: ${{ inputs.config-file }}"
            echo "path=${{ inputs.config-file }}" >> "$GITHUB_OUTPUT"
          else
            echo "No config file provided, using generated hugo.json"
            echo "path=hugo.json" >> "$GITHUB_OUTPUT"
          fi

      - if: ${{ inputs.build-readme-as-index }}
        name: Use README.md files as folder index
        run: |
          find "${{ inputs.path }}" -name 'README.md' -type f -execdir mv -v {} '_index.md' \;

      - id: pages
        name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Pull Docker image
        shell: bash
        run: docker pull "${{ inputs.docker-image }}"

      - name: Build with Hugo
        shell: bash
        run: |
          docker run \
            --rm \
            --volume "$PWD:/work" \
            --workdir /work \
            "${{ inputs.docker-image }}" \
            sh -c "
              cd '${{ inputs.path }}';
              [ -f go.mod ] || hugo mod init 'github.com/${{ github.repository }}';
              hugo mod get -u \
              && hugo \
                --baseURL '${{ steps.pages.outputs.base_url }}' \
                --config '${{ steps.config-file-path.outputs.path }}' \
                --gc \
                --minify
            "

      - name: Create GitHub Pages-compatible artifact
        shell: bash
        run: |
          set -euo pipefail
          tar \
          --create \
          --dereference \
          --directory "${{ inputs.path }}/public" \
          --exclude-from=<(echo -e '${{ inputs.exclude }}') \
          --file "${{ runner.temp }}/artifact.tar" \
          --hard-dereference \
          --verbose \
          .

      - name: Upload GitHub Pages artifacts
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
