---
name: Build Hugo site

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build with Hugo
        uses: docker://hugomods/hugo:std-go-git
        with:
          args: >
            sh -c "
                [ -f go.mod ] || hugo mod init 'github.com/${{ github.repository }}' \
                && hugo mod get -u \
                && hugo \
                  --gc \
                  --minify
            "
      - name: Upload GitHub Pages artifacts
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: github-pages
          path: public
